In [1]:
import arviz as az
import bambi as bmb
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import pymc as pm

print(f"Running on PyMC v{pm.__version__}")
import statsmodels.api as sm

from matplotlib.lines import Line2D

Running on PyMC v5.25.1

In [2]:
SEED = 1234
az.style.use("arviz-darkgrid")
plt.rcParams["figure.dpi"] = 300

In [3]:
# read the data
data = pd.read_csv('data/EAST_Data_Overview.csv')

data["SleepOrder"] = pd.to_numeric(data["SleepOrder"], errors="coerce")
data["SleepCondition"] = pd.to_numeric(data["SleepCondition"], errors="coerce")

# Recode: 1 -> -1, 2 -> 1
data["SleepOrder"] = data["SleepOrder"].replace({1: -1, 2: 1})
data["SleepCondition"] = data["SleepCondition"].replace({1: -1, 2: 1})

# print the first few rows of the data
print(data.head())
print(data.shape)

   VPN  SleepOrder  SleepCondition  pMisses  pPrematireResp  pNoSEva  nOKTr  \
0    1          -1               1      1.2             0.0      1.3    987
1    2          -1               1      1.0             0.1      1.4    985
2    3          -1               1      0.9             0.2      2.1    978
3    4          -1               1      0.3             0.1      0.5    994
4    6           1               1      2.2             0.0      3.3    967

   nErrorall    pErrall  nArwareErr  ...  ESS  PVT_Standard  PVT_Standard_SD  \
0        179  18.135765          47  ...   16      540.5493        162.09916
1         67   6.802030          40  ...   11      593.0541        217.96700
2        186  19.018405          65  ...   15      521.9296         80.18698
3        166  16.700201          49  ...    4      493.4177         43.80423
4         99  10.237849          55  ...   16      495.6842         90.05749

   PVT_novel  PVT_novel_SD  PVT_misses  Occ_State1  Occ_State2  Dwell_State1  \
0   550.9231      62.93841          53    0.252826    0.747174    123.000000
1   551.5385      99.47664          64    0.304527    0.695473     98.666667
2   547.6923     126.94053          47    0.437630    0.562370    210.500000
3   523.3571      40.28095          40    0.225709    0.774291    111.500000
4   455.6923      75.80390          36    0.000000    1.000000           NaN

   Dwell_State2
0    242.333333
1    225.333333
2    541.000000
3    382.500000
4    941.000000

[5 rows x 34 columns]
(60, 34)

# Sleep questionnaires

In [4]:
model = bmb.Model("KSS ~ SleepCondition + SleepOrder + (1|VPN)", data)
idata = model.fit(draws=2000, chains=4, random_seed=SEED,mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCondition, SleepOrder, 1|VPN_sigma, 1|VPN_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.
There were 40 divergences after tuning. Increase `target_accept` or reparameterize.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,1.421,0.187,1.077,1.791,0.005,0.002,1660.0,2623.0,1.0
Intercept,5.240,0.244,4.743,5.704,0.004,0.003,4508.0,3800.0,1.0
SleepCondition,1.507,0.184,1.145,1.873,0.002,0.003,8851.0,5730.0,1.0
SleepOrder,-0.326,0.183,-0.672,0.038,0.002,0.002,7184.0,5208.0,1.0
1|VPN_sigma,0.773,0.346,0.017,1.338,0.010,0.005,1146.0,2075.0,1.0
1|VPN[1],0.110,0.599,-1.091,1.383,0.007,0.009,7052.0,4308.0,1.0
1|VPN[2],0.091,0.605,-1.106,1.332,0.007,0.008,7054.0,4987.0,1.0
1|VPN[3],0.098,0.605,-1.164,1.296,0.008,0.008,6487.0,5091.0,1.0
1|VPN[4],0.097,0.596,-1.068,1.364,0.008,0.010,6216.0,5083.0,1.0
1|VPN[6],0.845,0.764,-0.351,2.441,0.016,0.009,2200.0,4197.0,1.0
1|VPN[7],-0.086,0.590,-1.307,1.101,0.008,0.010,5619.0,4403.0,1.0
1|VPN[8],0.363,0.635,-0.880,1.644,0.010,0.009,4385.0,4787.0,1.0
1|VPN[14],-0.098,0.610,-1.348,1.155,0.008,0.009,5819.0,4534.0,1.0
1|VPN[15],0.103,0.597,-1.107,1.345,0.007,0.009,6158.0,4905.0,1.0
1|VPN[19],0.094,0.599,-1.121,1.308,0.007,0.008,7090.0,5066.0,1.0
1|VPN[20],-0.827,0.750,-2.325,0.422,0.016,0.008,2271.0,4365.0,1.0
1|VPN[21],-1.033,0.835,-2.647,0.345,0.019,0.009,1892.0,3308.0,1.0
1|VPN[22],-0.279,0.641,-1.666,0.891,0.009,0.009,5625.0,4860.0,1.0
1|VPN[23],-0.270,0.617,-1.488,0.989,0.008,0.008,5616.0,4667.0,1.0
1|VPN[26],-0.466,0.651,-1.844,0.693,0.012,0.009,3361.0,5016.0,1.0
1|VPN[28],-0.833,0.760,-2.390,0.394,0.017,0.008,2092.0,4813.0,1.0
1|VPN[29],0.289,0.639,-0.973,1.594,0.009,0.009,5244.0,4896.0,1.0
1|VPN[30],0.469,0.653,-0.716,1.846,0.010,0.008,4060.0,4021.0,1.0
1|VPN[32],0.647,0.705,-0.619,2.056,0.012,0.009,3249.0,4907.0,1.0
1|VPN[33],-0.090,0.591,-1.321,1.120,0.007,0.009,6572.0,3526.0,1.0
1|VPN[34],0.278,0.616,-0.867,1.613,0.008,0.008,6140.0,5145.0,1.0
1|VPN[36],-0.080,0.607,-1.250,1.223,0.007,0.009,6851.0,4899.0,1.0
1|VPN[37],0.274,0.612,-0.858,1.602,0.008,0.009,5324.0,5162.0,1.0
1|VPN[38],-0.093,0.592,-1.338,1.083,0.007,0.009,6502.0,4312.0,1.0
1|VPN[39],0.283,0.617,-0.847,1.630,0.008,0.009,5789.0,5150.0,1.0
1|VPN[40],-0.454,0.644,-1.861,0.682,0.010,0.009,4466.0,4169.0,1.0
1|VPN[41],-0.833,0.766,-2.451,0.387,0.016,0.009,2358.0,4360.0,1.0
1|VPN[42],0.108,0.606,-0.993,1.489,0.008,0.009,6137.0,4384.0,1.0
1|VPN[43],0.835,0.758,-0.374,2.457,0.017,0.008,2090.0,4385.0,1.0
1|VPN[45],0.464,0.647,-0.695,1.880,0.010,0.008,3951.0,4672.0,1.0

In [5]:
model = bmb.Model("PVT_misses ~ SleepCondition + SleepOrder + (1|VPN)", data)
idata = model.fit(draws=2000, chains=4, random_seed=SEED,mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCondition, SleepOrder, 1|VPN_sigma, 1|VPN_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,11.846,1.714,8.842,15.199,0.035,0.027,2446.0,3700.0,1.0
Intercept,44.073,3.648,36.737,51.163,0.087,0.052,1767.0,2544.0,1.0
SleepCondition,3.195,1.534,0.324,6.403,0.016,0.020,9094.0,5636.0,1.0
SleepOrder,2.414,1.550,-0.724,5.333,0.016,0.019,9717.0,6100.0,1.0
1|VPN_sigma,17.707,3.087,11.611,23.651,0.077,0.048,1610.0,2812.0,1.0
1|VPN[1],-1.708,7.999,-16.653,14.615,0.105,0.091,5827.0,5698.0,1.0
1|VPN[2],18.035,8.271,1.846,34.245,0.106,0.092,6058.0,5906.0,1.0
1|VPN[3],-8.532,7.985,-23.721,7.560,0.100,0.090,6304.0,6075.0,1.0
1|VPN[4],1.150,8.103,-15.230,16.659,0.106,0.094,5818.0,5267.0,1.0
1|VPN[6],-15.726,8.260,-32.644,0.084,0.112,0.109,5350.0,5163.0,1.0
1|VPN[7],23.761,8.501,7.382,40.700,0.115,0.096,5462.0,5195.0,1.0
1|VPN[8],28.606,8.601,11.457,45.028,0.128,0.087,4531.0,5820.0,1.0
1|VPN[14],-11.263,8.170,-27.572,4.908,0.106,0.099,5926.0,5031.0,1.0
1|VPN[15],29.053,8.544,12.561,46.298,0.119,0.100,5145.0,5113.0,1.0
1|VPN[19],-6.826,8.072,-21.974,9.787,0.098,0.091,6847.0,5612.0,1.0
1|VPN[20],18.328,8.302,1.691,33.776,0.110,0.088,5670.0,6235.0,1.0
1|VPN[21],-7.225,8.208,-23.573,9.236,0.105,0.107,6057.0,5261.0,1.0
1|VPN[22],-6.877,8.176,-22.276,9.748,0.103,0.094,6280.0,5137.0,1.0
1|VPN[23],-17.831,8.266,-33.163,-0.750,0.111,0.090,5588.0,5222.0,1.0
1|VPN[26],-4.347,8.107,-20.107,11.862,0.103,0.090,6237.0,5075.0,1.0
1|VPN[28],-3.270,8.126,-19.388,12.517,0.110,0.095,5515.0,5697.0,1.0
1|VPN[29],20.020,8.423,3.095,35.992,0.113,0.097,5571.0,5377.0,1.0
1|VPN[30],19.335,8.196,3.587,35.846,0.109,0.098,5601.0,5727.0,1.0
1|VPN[32],-14.857,8.318,-30.908,1.811,0.106,0.092,6149.0,5933.0,1.0
1|VPN[33],2.728,8.184,-13.552,18.122,0.106,0.096,5972.0,6119.0,1.0
1|VPN[34],-20.282,8.310,-36.846,-4.068,0.111,0.100,5638.0,5478.0,1.0
1|VPN[36],-23.826,8.485,-40.983,-8.177,0.120,0.089,4962.0,6079.0,1.0
1|VPN[37],5.109,8.231,-10.454,22.027,0.107,0.101,5914.0,5020.0,1.0
1|VPN[38],-16.103,8.285,-32.504,0.227,0.105,0.097,6226.0,5345.0,1.0
1|VPN[39],6.839,8.137,-8.902,23.147,0.111,0.103,5348.0,5367.0,1.0
1|VPN[40],17.950,8.367,1.625,34.441,0.114,0.097,5404.0,5851.0,1.0
1|VPN[41],-14.093,8.296,-30.750,1.584,0.106,0.097,6145.0,5211.0,1.0
1|VPN[42],-6.466,8.176,-22.041,9.802,0.105,0.105,5994.0,5110.0,1.0
1|VPN[43],-5.736,8.125,-21.983,10.100,0.107,0.096,5700.0,5724.0,1.0
1|VPN[45],-7.709,8.209,-23.451,8.422,0.107,0.092,5887.0,6426.0,1.0

# Error rate

In [6]:
model = bmb.Model("pErrall ~ SleepCondition + SleepOrder + (1|VPN)", data)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED,mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCondition, SleepOrder, 1|VPN_sigma, 1|VPN_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,3.694,0.542,2.760,4.800,0.011,0.010,2529.0,2577.0,1.0
Intercept,10.661,0.944,8.891,12.603,0.019,0.012,2480.0,3971.0,1.0
SleepCondition,1.547,0.481,0.581,2.465,0.005,0.006,10721.0,5736.0,1.0
SleepOrder,-0.710,0.490,-1.627,0.283,0.005,0.007,10548.0,5252.0,1.0
1|VPN_sigma,4.213,0.904,2.502,6.085,0.021,0.017,1982.0,2317.0,1.0
1|VPN[1],2.179,2.284,-2.301,6.629,0.029,0.028,6047.0,5010.0,1.0
1|VPN[2],-2.532,2.352,-6.939,2.266,0.029,0.025,6761.0,5999.0,1.0
1|VPN[3],0.639,2.279,-3.905,4.949,0.026,0.025,7488.0,5615.0,1.0
1|VPN[4],3.460,2.394,-1.097,8.223,0.031,0.026,5872.0,5776.0,1.0
1|VPN[6],-0.325,2.277,-4.883,3.993,0.025,0.027,8068.0,5732.0,1.0
1|VPN[7],-5.022,2.421,-9.768,-0.265,0.033,0.029,5327.0,3964.0,1.0
1|VPN[8],7.678,2.694,2.443,12.966,0.045,0.035,3746.0,3172.0,1.0
1|VPN[14],-3.752,2.386,-8.550,0.800,0.031,0.026,5818.0,5999.0,1.0
1|VPN[15],-0.099,2.260,-4.309,4.507,0.026,0.027,7336.0,5808.0,1.0
1|VPN[19],-1.997,2.303,-6.514,2.528,0.028,0.026,6865.0,5861.0,1.0
1|VPN[20],2.044,2.308,-2.415,6.563,0.029,0.027,6224.0,5005.0,1.0
1|VPN[21],-2.633,2.322,-7.344,1.785,0.028,0.027,6703.0,5242.0,1.0
1|VPN[22],-1.257,2.312,-5.639,3.374,0.026,0.025,8012.0,6327.0,1.0
1|VPN[23],-0.852,2.306,-5.486,3.614,0.024,0.029,9084.0,5510.0,1.0
1|VPN[26],-0.959,2.310,-5.608,3.490,0.028,0.026,6934.0,5591.0,1.0
1|VPN[28],-0.926,2.287,-5.322,3.650,0.026,0.025,7554.0,5912.0,1.0
1|VPN[29],7.133,2.590,1.926,12.027,0.044,0.031,3604.0,3533.0,1.0
1|VPN[30],-1.959,2.269,-6.267,2.604,0.027,0.025,6851.0,6277.0,1.0
1|VPN[32],5.921,2.562,0.893,11.013,0.039,0.031,4399.0,3970.0,1.0
1|VPN[33],3.429,2.357,-1.176,7.991,0.031,0.026,5736.0,5812.0,1.0
1|VPN[34],-3.784,2.330,-8.432,0.728,0.033,0.025,5113.0,6008.0,1.0
1|VPN[36],3.570,2.370,-1.122,8.194,0.031,0.027,5691.0,5706.0,1.0
1|VPN[37],4.661,2.465,-0.161,9.348,0.034,0.030,5185.0,4671.0,1.0
1|VPN[38],-3.298,2.314,-7.875,1.174,0.029,0.026,6214.0,5683.0,1.0
1|VPN[39],-0.110,2.309,-4.415,4.598,0.027,0.027,7450.0,6080.0,1.0
1|VPN[40],-2.333,2.328,-6.940,2.131,0.031,0.026,5776.0,5518.0,1.0
1|VPN[41],-0.746,2.351,-5.317,3.871,0.027,0.026,7607.0,5827.0,1.0
1|VPN[42],-4.208,2.416,-8.736,0.664,0.032,0.025,5599.0,5858.0,1.0
1|VPN[43],-1.836,2.338,-6.388,2.724,0.027,0.028,7393.0,5991.0,1.0
1|VPN[45],-2.110,2.349,-6.584,2.614,0.028,0.026,7202.0,5865.0,1.0

In [7]:
model = bmb.Model("pAwareErr ~ SleepCondition + SleepOrder + (1|VPN)", data)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED,mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCondition, SleepOrder, 1|VPN_sigma, 1|VPN_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 8 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,9.042,1.297,6.653,11.562,0.025,0.016,2610.0,4225.0,1.0
Intercept,48.947,3.338,42.464,55.778,0.084,0.054,1578.0,2265.0,1.0
SleepCondition,-3.344,1.169,-5.592,-0.961,0.012,0.014,10122.0,6216.0,1.0
SleepOrder,-1.414,1.194,-3.679,1.023,0.012,0.016,9905.0,5565.0,1.0
1|VPN_sigma,16.551,2.676,11.712,22.101,0.067,0.046,1608.0,2460.0,1.0
1|VPN[1],-15.763,6.697,-28.937,-2.692,0.100,0.076,4518.0,5136.0,1.0
1|VPN[2],8.869,6.652,-3.795,22.118,0.102,0.072,4287.0,5679.0,1.0
1|VPN[3],-10.198,6.647,-22.976,3.092,0.097,0.076,4695.0,4859.0,1.0
1|VPN[4],-17.768,6.627,-30.926,-4.622,0.100,0.071,4432.0,5581.0,1.0
1|VPN[6],2.570,6.659,-10.406,15.458,0.092,0.073,5277.0,5751.0,1.0
1|VPN[7],-0.333,6.577,-13.368,12.747,0.093,0.071,5006.0,5635.0,1.0
1|VPN[8],-15.496,6.708,-28.846,-2.782,0.099,0.071,4612.0,5620.0,1.0
1|VPN[14],25.546,6.905,12.416,39.321,0.106,0.078,4205.0,5143.0,1.0
1|VPN[15],-14.078,6.758,-27.471,-0.939,0.099,0.073,4613.0,5475.0,1.0
1|VPN[19],10.151,6.724,-3.075,23.072,0.097,0.072,4845.0,5732.0,1.0
1|VPN[20],-4.855,6.633,-17.737,8.114,0.095,0.075,4854.0,5868.0,1.0
1|VPN[21],10.042,6.722,-2.964,23.458,0.097,0.082,4735.0,5623.0,1.0
1|VPN[22],6.044,6.683,-6.936,19.292,0.096,0.077,4821.0,5069.0,1.0
1|VPN[23],18.584,6.762,5.899,32.183,0.097,0.076,4794.0,5678.0,1.0
1|VPN[26],-2.828,6.673,-15.967,10.103,0.092,0.085,5252.0,5470.0,1.0
1|VPN[28],16.635,6.768,2.603,29.346,0.094,0.082,5228.0,5335.0,1.0
1|VPN[29],-28.249,6.876,-41.523,-14.673,0.103,0.074,4466.0,5214.0,1.0
1|VPN[30],-6.685,6.665,-19.314,6.915,0.092,0.074,5255.0,5221.0,1.0
1|VPN[32],-0.740,6.565,-13.694,11.682,0.093,0.075,4959.0,5108.0,1.0
1|VPN[33],13.508,6.562,0.392,26.067,0.098,0.073,4458.0,5044.0,1.0
1|VPN[34],18.459,6.732,4.969,31.493,0.100,0.075,4538.0,5217.0,1.0
1|VPN[36],-33.250,7.019,-46.996,-19.663,0.110,0.070,4113.0,5621.0,1.0
1|VPN[37],-21.009,6.837,-34.983,-7.874,0.096,0.071,5035.0,5330.0,1.0
1|VPN[38],6.478,6.568,-5.906,19.738,0.096,0.073,4672.0,5272.0,1.0
1|VPN[39],8.291,6.667,-4.597,21.394,0.099,0.072,4497.0,5250.0,1.0
1|VPN[40],5.599,6.652,-6.737,19.248,0.096,0.076,4781.0,4906.0,1.0
1|VPN[41],11.312,6.753,-1.130,25.369,0.098,0.076,4780.0,5610.0,1.0
1|VPN[42],-7.966,6.668,-21.350,4.600,0.092,0.071,5227.0,4610.0,1.0
1|VPN[43],0.709,6.689,-12.076,14.385,0.095,0.084,4960.0,5002.0,1.0
1|VPN[45],17.072,6.904,3.189,30.138,0.104,0.083,4359.0,5455.0,1.0

In [8]:
model = bmb.Model("pMisses ~ SleepCondition + SleepOrder + (1|VPN)", data)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED,mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCondition, SleepOrder, 1|VPN_sigma, 1|VPN_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,2.144,0.282,1.617,2.690,0.005,0.003,2700.0,4478.0,1.0
Intercept,1.492,0.366,0.774,2.204,0.004,0.004,7188.0,5529.0,1.0
SleepCondition,0.885,0.285,0.311,1.433,0.002,0.005,14949.0,4949.0,1.0
SleepOrder,0.253,0.278,-0.322,0.788,0.003,0.004,11654.0,4876.0,1.0
1|VPN_sigma,1.134,0.515,0.019,1.966,0.014,0.007,1376.0,1888.0,1.0
1|VPN[1],-0.297,0.909,-2.211,1.482,0.010,0.013,8051.0,5768.0,1.0
1|VPN[2],-0.263,0.915,-2.221,1.405,0.009,0.012,9856.0,6411.0,1.0
1|VPN[3],-0.354,0.880,-2.140,1.341,0.010,0.011,8018.0,5916.0,1.0
1|VPN[4],-0.478,0.930,-2.421,1.298,0.012,0.012,6151.0,5187.0,1.0
1|VPN[6],-0.079,0.890,-1.762,1.824,0.009,0.013,10787.0,5963.0,1.0
1|VPN[7],-0.515,0.916,-2.358,1.266,0.012,0.012,6330.0,5732.0,1.0
1|VPN[8],1.439,1.234,-0.514,3.893,0.024,0.011,2523.0,5992.0,1.0
1|VPN[14],-0.501,0.939,-2.474,1.302,0.012,0.014,6735.0,5136.0,1.0
1|VPN[15],-0.266,0.892,-2.098,1.539,0.009,0.013,10807.0,5853.0,1.0
1|VPN[19],-0.427,0.915,-2.300,1.334,0.011,0.011,7631.0,5934.0,1.0
1|VPN[20],0.160,0.895,-1.601,2.051,0.009,0.012,10117.0,6102.0,1.0
1|VPN[21],-0.449,0.939,-2.407,1.388,0.011,0.012,7520.0,5634.0,1.0
1|VPN[22],-0.199,0.900,-2.080,1.592,0.008,0.013,11246.0,5327.0,1.0
1|VPN[23],0.073,0.898,-1.711,1.941,0.008,0.013,12888.0,5778.0,1.0
1|VPN[26],1.391,1.194,-0.587,3.778,0.024,0.011,2523.0,5624.0,1.0
1|VPN[28],-0.305,0.889,-2.168,1.413,0.009,0.012,9409.0,6183.0,1.0
1|VPN[29],0.129,0.897,-1.641,2.063,0.009,0.013,11321.0,5341.0,1.0
1|VPN[30],0.378,0.914,-1.451,2.256,0.010,0.012,8542.0,5778.0,1.0
1|VPN[32],2.511,1.696,-0.310,5.518,0.041,0.015,1635.0,2819.0,1.0
1|VPN[33],-0.150,0.887,-1.913,1.677,0.009,0.012,10365.0,5635.0,1.0
1|VPN[34],-0.074,0.889,-1.867,1.768,0.008,0.013,11704.0,5644.0,1.0
1|VPN[36],-0.076,0.882,-1.973,1.616,0.009,0.012,10517.0,6191.0,1.0
1|VPN[37],0.870,1.024,-0.937,3.030,0.016,0.011,4119.0,5369.0,1.0
1|VPN[38],-0.453,0.904,-2.335,1.260,0.010,0.011,7860.0,6071.0,1.0
1|VPN[39],-0.320,0.925,-2.203,1.547,0.010,0.013,8867.0,6365.0,1.0
1|VPN[40],-0.435,0.926,-2.398,1.343,0.010,0.012,8139.0,6469.0,1.0
1|VPN[41],-0.420,0.923,-2.348,1.338,0.010,0.012,7807.0,6086.0,1.0
1|VPN[42],-0.459,0.936,-2.506,1.264,0.012,0.011,6586.0,5955.0,1.0
1|VPN[43],-0.211,0.902,-2.156,1.541,0.009,0.014,10159.0,5560.0,1.0
1|VPN[45],-0.184,0.908,-2.047,1.647,0.008,0.012,11829.0,5645.0,1.0

In [9]:
model = bmb.Model("RT ~ SleepCondition + SleepOrder + (1|VPN)", data)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED,mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCondition, SleepOrder, 1|VPN_sigma, 1|VPN_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,0.045,0.006,0.033,0.057,0.000,0.0,2298.0,3132.0,1.0
Intercept,0.626,0.021,0.581,0.666,0.001,0.0,1322.0,2269.0,1.0
SleepCondition,0.011,0.006,-0.000,0.023,0.000,0.0,9966.0,5065.0,1.0
SleepOrder,-0.040,0.006,-0.052,-0.029,0.000,0.0,9722.0,5863.0,1.0
1|VPN_sigma,0.112,0.017,0.080,0.146,0.000,0.0,1382.0,1635.0,1.0
1|VPN[1],0.036,0.037,-0.036,0.107,0.001,0.0,3514.0,5096.0,1.0
1|VPN[2],-0.010,0.036,-0.084,0.057,0.001,0.0,3152.0,4438.0,1.0
1|VPN[3],0.006,0.036,-0.060,0.080,0.001,0.0,3604.0,4893.0,1.0
1|VPN[4],-0.087,0.037,-0.160,-0.016,0.001,0.0,3469.0,5024.0,1.0
1|VPN[6],-0.001,0.036,-0.073,0.068,0.001,0.0,3428.0,5114.0,1.0
1|VPN[7],-0.079,0.037,-0.152,-0.007,0.001,0.0,3333.0,4477.0,1.0
1|VPN[8],0.212,0.037,0.141,0.287,0.001,0.0,3185.0,5459.0,1.0
1|VPN[14],-0.140,0.036,-0.212,-0.069,0.001,0.0,3337.0,4069.0,1.0
1|VPN[15],0.075,0.036,0.007,0.148,0.001,0.0,3215.0,4694.0,1.0
1|VPN[19],-0.125,0.037,-0.197,-0.054,0.001,0.0,3496.0,5512.0,1.0
1|VPN[20],-0.026,0.036,-0.098,0.044,0.001,0.0,3203.0,4606.0,1.0
1|VPN[21],-0.163,0.037,-0.236,-0.091,0.001,0.0,3402.0,5052.0,1.0
1|VPN[22],-0.049,0.037,-0.120,0.023,0.001,0.0,3262.0,4479.0,1.0
1|VPN[23],-0.025,0.036,-0.097,0.047,0.001,0.0,3122.0,4563.0,1.0
1|VPN[26],0.085,0.037,0.013,0.159,0.001,0.0,3119.0,4808.0,1.0
1|VPN[28],0.035,0.038,-0.033,0.113,0.001,0.0,3780.0,4804.0,1.0
1|VPN[29],-0.026,0.037,-0.100,0.044,0.001,0.0,3403.0,4907.0,1.0
1|VPN[30],0.197,0.037,0.126,0.269,0.001,0.0,2923.0,4871.0,1.0
1|VPN[32],0.151,0.037,0.077,0.224,0.001,0.0,3235.0,5084.0,1.0
1|VPN[33],0.028,0.037,-0.047,0.096,0.001,0.0,3450.0,4853.0,1.0
1|VPN[34],-0.102,0.036,-0.174,-0.032,0.001,0.0,3763.0,5059.0,1.0
1|VPN[36],0.152,0.038,0.078,0.226,0.001,0.0,3274.0,4836.0,1.0
1|VPN[37],0.120,0.037,0.046,0.192,0.001,0.0,3080.0,4925.0,1.0
1|VPN[38],-0.094,0.036,-0.162,-0.018,0.001,0.0,3563.0,4891.0,1.0
1|VPN[39],-0.107,0.037,-0.177,-0.034,0.001,0.0,3284.0,4628.0,1.0
1|VPN[40],0.005,0.037,-0.066,0.077,0.001,0.0,3610.0,4276.0,1.0
1|VPN[41],-0.072,0.037,-0.142,0.002,0.001,0.0,3243.0,4724.0,1.0
1|VPN[42],-0.140,0.036,-0.209,-0.066,0.001,0.0,3247.0,5047.0,1.0
1|VPN[43],0.090,0.037,0.017,0.162,0.001,0.0,3094.0,4741.0,1.0
1|VPN[45],0.075,0.037,0.002,0.146,0.001,0.0,3243.0,5102.0,1.0

In [10]:
data3 = df = pd.read_csv("data/EAST_Data_ErrD_Qs.csv", header=0)

# Recode: 1 -> -1, 2 -> 1
data3["SleepOrder"] = data3["SleepOrder"].replace({1: -1, 2: 1})
data3["SleepCond"] = data3["SleepCond"].replace({1: -1, 2: 1})
# print the first few rows of the data
print(data3.head())
print(data3.shape)

   SubID  SleepCond  SleepOrder     Q1_ErrD     Q2_ErrD     Q3_ErrD
0      1         -1          -1  342.324299  247.623971  287.157588
1      1          1          -1  577.761678  499.206486  563.135529
2      2         -1          -1  191.879571  180.955979  306.151249
3      2          1          -1  179.097789  173.186309  226.206502
4      3         -1          -1  152.059508   99.018813  114.136950
(60, 6)

In [11]:
model = bmb.Model("Q1_ErrD ~ SleepCond + SleepOrder + (1|SubID)", data3)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED, mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCond, SleepOrder, 1|SubID_sigma, 1|SubID_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.
There was 1 divergence after tuning. Increase `target_accept` or reparameterize.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,136.851,18.850,103.210,175.225,0.425,0.225,1986.0,3407.0,1.0
Intercept,323.111,25.532,274.528,374.863,0.355,0.360,5259.0,3860.0,1.0
SleepCond,8.438,17.815,-26.812,43.800,0.151,0.230,13863.0,5710.0,1.0
SleepOrder,-13.339,25.211,-63.396,37.468,0.364,0.299,4843.0,4705.0,1.0
1|SubID_sigma,90.979,34.962,16.268,158.250,0.984,0.616,1286.0,1276.0,1.0
1|SubID[1],57.350,70.504,-71.152,205.608,0.997,0.835,5157.0,4923.0,1.0
1|SubID[2],-69.462,73.635,-219.737,59.181,1.095,0.788,4478.0,6028.0,1.0
1|SubID[3],11.575,65.043,-113.057,149.119,0.709,0.871,8419.0,6125.0,1.0
1|SubID[4],54.166,68.953,-68.381,200.919,0.981,0.753,5025.0,5695.0,1.0
1|SubID[5],10.166,66.953,-123.402,143.033,0.768,0.861,7691.0,5541.0,1.0
1|SubID[6],-59.347,70.497,-202.323,69.539,1.044,0.783,4648.0,5887.0,1.0
1|SubID[7],99.761,80.220,-43.473,255.187,1.474,0.790,2924.0,5521.0,1.0
1|SubID[8],-90.781,78.333,-253.634,43.202,1.359,0.909,3239.0,4604.0,1.0
1|SubID[9],40.901,68.430,-90.514,180.501,0.832,0.825,6822.0,6144.0,1.0
1|SubID[10],-57.517,72.319,-209.386,73.087,0.975,0.941,5633.0,4834.0,1.0
1|SubID[11],36.236,67.792,-96.390,174.224,0.814,0.907,7187.0,4890.0,1.0
1|SubID[12],-33.233,67.507,-168.862,99.564,0.808,0.822,6997.0,5990.0,1.0
1|SubID[13],-25.357,66.998,-172.392,94.796,0.707,0.854,9021.0,6370.0,1.0
1|SubID[14],-44.710,69.078,-178.287,92.482,0.866,0.812,6448.0,5383.0,1.0
1|SubID[15],-49.796,69.518,-198.940,73.370,0.950,0.807,5501.0,5409.0,1.0
1|SubID[16],-15.924,66.490,-149.124,117.139,0.741,0.836,8155.0,6467.0,1.0
1|SubID[17],109.390,82.917,-40.191,270.520,1.582,0.833,2652.0,4832.0,1.0
1|SubID[18],-41.679,69.388,-180.018,95.285,0.883,0.807,6210.0,5397.0,1.0
1|SubID[19],110.634,83.942,-43.008,265.137,1.617,0.896,2667.0,5297.0,1.0
1|SubID[20],94.050,79.130,-37.481,260.464,1.469,0.811,2926.0,4998.0,1.0
1|SubID[21],-84.752,75.562,-234.937,53.152,1.260,0.829,3531.0,4967.0,1.0
1|SubID[22],50.886,70.201,-84.973,188.479,0.968,0.868,5444.0,5423.0,1.0
1|SubID[23],87.117,77.635,-54.589,243.026,1.267,0.864,3779.0,5214.0,1.0
1|SubID[24],-42.037,68.988,-188.147,85.939,0.893,0.922,6107.0,4740.0,1.0
1|SubID[25],-12.775,66.677,-143.348,123.180,0.711,0.892,8872.0,5429.0,1.0
1|SubID[26],-28.459,68.168,-170.905,103.359,0.826,0.829,6915.0,5897.0,1.0
1|SubID[27],-13.675,66.227,-157.162,110.649,0.707,0.869,8747.0,4884.0,1.0
1|SubID[28],-60.127,72.003,-204.047,72.394,1.006,0.898,5138.0,4668.0,1.0
1|SubID[29],-5.395,65.321,-138.451,123.548,0.668,0.844,9636.0,6073.0,1.0
1|SubID[30],-16.235,66.241,-150.918,113.080,0.793,0.949,7044.0,5277.0,1.0

In [12]:
model = bmb.Model("Q2_ErrD ~ SleepCond + SleepOrder + (1|SubID)", data3)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED, mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCond, SleepOrder, 1|SubID_sigma, 1|SubID_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 10 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,116.365,16.782,86.003,150.342,0.454,0.345,1726.0,2356.0,1.0
Intercept,291.033,28.963,232.440,347.261,0.547,0.368,2806.0,4051.0,1.0
SleepCond,44.261,14.854,15.891,75.009,0.149,0.195,9879.0,5204.0,1.0
SleepOrder,-15.104,28.673,-70.040,43.606,0.550,0.387,2719.0,3780.0,1.0
1|SubID_sigma,129.354,28.886,71.755,185.076,0.767,0.650,1527.0,1998.0,1.0
1|SubID[1],47.186,72.479,-93.818,189.563,0.899,0.758,6556.0,6118.0,1.0
1|SubID[2],-88.796,76.596,-241.846,55.690,1.048,0.814,5333.0,5519.0,1.0
1|SubID[3],6.336,71.777,-137.017,144.712,0.905,0.827,6261.0,5845.0,1.0
1|SubID[4],108.497,76.840,-36.727,260.497,1.075,0.831,5097.0,5587.0,1.0
1|SubID[5],5.718,74.144,-141.686,150.952,0.963,0.903,5950.0,4517.0,1.0
1|SubID[6],-137.619,78.561,-294.939,9.693,1.252,0.803,3918.0,4324.0,1.0
1|SubID[7],271.555,92.162,90.361,458.039,1.864,1.370,2597.0,2319.0,1.0
1|SubID[8],-100.855,75.455,-240.648,49.076,1.095,0.780,4756.0,6161.0,1.0
1|SubID[9],-16.383,74.450,-160.028,132.675,0.967,0.862,5933.0,5339.0,1.0
1|SubID[10],-43.127,73.809,-189.033,98.734,0.929,0.861,6317.0,5716.0,1.0
1|SubID[11],62.920,74.696,-87.416,207.581,0.944,0.822,6249.0,5835.0,1.0
1|SubID[12],-45.750,74.607,-191.077,100.236,0.985,0.811,5743.0,5535.0,1.0
1|SubID[13],45.984,75.882,-100.212,197.923,0.971,0.833,6106.0,5414.0,1.0
1|SubID[14],-27.736,73.391,-171.524,113.585,0.882,0.848,6948.0,6222.0,1.0
1|SubID[15],-28.937,74.454,-184.127,108.118,0.959,0.841,5999.0,5699.0,1.0
1|SubID[16],-36.462,75.260,-182.754,109.435,0.956,0.836,6206.0,6149.0,1.0
1|SubID[17],187.610,81.459,18.375,340.203,1.444,0.927,3210.0,2974.0,1.0
1|SubID[18],-68.858,74.884,-218.919,75.699,0.959,0.807,6074.0,5972.0,1.0
1|SubID[19],158.916,80.931,-5.015,316.261,1.335,0.868,3674.0,3049.0,1.0
1|SubID[20],126.551,78.813,-24.763,281.006,1.170,0.863,4538.0,5087.0,1.0
1|SubID[21],-115.229,77.167,-268.530,31.090,1.137,0.862,4593.0,5273.0,1.0
1|SubID[22],121.937,77.468,-27.001,271.260,1.142,0.792,4564.0,5290.0,1.0
1|SubID[23],86.482,77.070,-66.365,234.070,1.051,0.840,5388.0,5429.0,1.0
1|SubID[24],-101.404,76.226,-249.738,46.743,1.029,0.827,5477.0,5740.0,1.0
1|SubID[25],-16.056,73.351,-161.761,127.326,0.894,0.813,6737.0,5939.0,1.0
1|SubID[26],-66.771,74.923,-219.298,78.240,1.023,0.838,5364.0,5328.0,1.0
1|SubID[27],-64.395,74.642,-217.219,78.159,0.960,0.798,6057.0,5511.0,1.0
1|SubID[28],-140.167,78.940,-296.556,11.043,1.267,0.848,3860.0,4420.0,1.0
1|SubID[29],-52.969,74.583,-201.263,87.809,0.960,0.811,6037.0,5675.0,1.0
1|SubID[30],-59.612,75.848,-207.169,91.387,0.980,0.813,5981.0,5643.0,1.0

In [13]:
model = bmb.Model("Q3_ErrD ~ SleepCond + SleepOrder + (1|SubID)", data3)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED, mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCond, SleepOrder, 1|SubID_sigma, 1|SubID_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,136.960,19.579,103.326,178.398,0.491,0.283,1663.0,3122.0,1.0
Intercept,328.982,28.595,270.872,382.977,0.499,0.386,3313.0,3929.0,1.0
SleepCond,70.334,18.216,32.913,104.443,0.188,0.237,9349.0,5360.0,1.0
SleepOrder,-22.563,28.811,-79.131,33.507,0.482,0.373,3613.0,3904.0,1.0
1|SubID_sigma,116.479,33.886,42.193,179.653,0.925,0.621,1385.0,1738.0,1.0
1|SubID[1],41.557,76.887,-102.791,198.664,1.020,0.955,5709.0,4814.0,1.0
1|SubID[2],-49.719,77.918,-206.124,99.078,1.054,0.889,5518.0,4801.0,1.0
1|SubID[3],2.856,74.419,-135.689,161.366,0.908,0.948,6643.0,5498.0,1.0
1|SubID[4],105.379,82.592,-49.341,271.397,1.423,0.941,3382.0,4985.0,1.0
1|SubID[5],-19.229,76.968,-174.010,131.353,0.932,0.963,6823.0,5783.0,1.0
1|SubID[6],-131.846,85.209,-295.164,30.511,1.513,0.949,3177.0,4316.0,1.0
1|SubID[7],192.681,96.287,-0.293,368.861,2.014,1.055,2267.0,2522.0,1.0
1|SubID[8],-98.538,81.424,-259.677,57.965,1.289,0.870,3976.0,5503.0,1.0
1|SubID[9],-19.078,75.594,-166.084,132.945,0.989,0.897,5829.0,4801.0,1.0
1|SubID[10],-49.097,79.040,-211.833,98.059,1.028,0.975,5875.0,5304.0,1.0
1|SubID[11],16.881,76.972,-140.923,166.602,0.949,0.922,6616.0,5428.0,1.0
1|SubID[12],-75.549,77.701,-235.850,67.142,1.147,0.875,4619.0,5320.0,1.0
1|SubID[13],-59.155,78.776,-219.229,86.640,1.043,0.902,5728.0,5205.0,1.0
1|SubID[14],32.881,76.093,-122.971,178.037,0.907,0.928,7090.0,5566.0,1.0
1|SubID[15],10.656,75.256,-134.461,163.082,0.958,0.910,6197.0,5344.0,1.0
1|SubID[16],-35.590,76.403,-189.523,111.888,1.013,0.920,5697.0,5037.0,1.0
1|SubID[17],204.493,97.552,2.509,382.709,2.120,1.091,2139.0,2453.0,1.0
1|SubID[18],6.185,75.208,-137.884,162.732,0.944,0.958,6334.0,5799.0,1.0
1|SubID[19],84.281,79.775,-72.451,239.588,1.108,0.843,5156.0,5620.0,1.0
1|SubID[20],67.656,77.519,-81.493,222.776,1.167,0.825,4446.0,4714.0,1.0
1|SubID[21],-105.233,82.291,-273.507,45.886,1.320,0.886,3839.0,5084.0,1.0
1|SubID[22],84.693,80.191,-58.158,251.795,1.201,0.889,4494.0,5053.0,1.0
1|SubID[23],75.574,80.468,-77.416,235.582,1.161,0.979,4900.0,4682.0,1.0
1|SubID[24],-109.533,83.283,-272.734,48.092,1.338,0.924,3880.0,5157.0,1.0
1|SubID[25],69.934,78.484,-80.246,219.590,1.168,0.914,4590.0,5168.0,1.0
1|SubID[26],-84.592,80.573,-244.500,64.725,1.224,0.881,4353.0,5067.0,1.0
1|SubID[27],0.680,79.288,-155.945,156.547,0.943,1.007,7058.0,4814.0,1.0
1|SubID[28],-82.533,79.997,-245.893,65.886,1.201,0.927,4456.0,4677.0,1.0
1|SubID[29],-39.087,76.215,-187.610,113.311,0.986,0.899,6035.0,5225.0,1.0
1|SubID[30],-42.683,76.369,-198.445,100.279,1.008,0.853,5761.0,5417.0,1.0

In [14]:
data4 = df = pd.read_csv("data/EAST_Data_UnAwErrD_Qs.csv", header=0)

# Recode: 1 -> -1, 2 -> 1
data4["SleepOrder"] = data4["SleepOrder"].replace({1: -1, 2: 1})
data4["SleepCond"] = data4["SleepCond"].replace({1: -1, 2: 1})
# print the first few rows of the data
print(data4.head())
print(data4.shape)

   SubID  SleepCond  SleepOrder  Q1_UnAwErrD  Q2_UnAwErrD  Q3_UnAwErrD
0      1         -1          -1   247.623971   152.383982   180.955979
1      1          1          -1   364.755278   384.918500   448.847543
2      2         -1          -1   115.687580    57.143993    96.639582
3      2          1          -1    82.808803    76.208299    85.715990
4      3         -1          -1    75.567117    70.446817    76.040955
(60, 6)

In [15]:
model = bmb.Model("Q1_UnAwErrD ~ SleepCond + SleepOrder + (1|SubID)", data4)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED, mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCond, SleepOrder, 1|SubID_sigma, 1|SubID_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 8 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,85.607,12.146,64.523,110.942,0.266,0.213,2249.0,2824.0,1.0
Intercept,178.424,21.486,136.590,221.059,0.444,0.317,2359.0,3517.0,1.0
SleepCond,5.356,11.191,-16.431,27.720,0.104,0.146,11577.0,5794.0,1.0
SleepOrder,-35.269,20.912,-77.020,5.266,0.420,0.272,2484.0,3712.0,1.0
1|SubID_sigma,94.645,21.305,55.223,137.695,0.557,0.430,1515.0,2334.0,1.0
1|SubID[1],63.943,55.025,-43.405,172.099,0.760,0.602,5252.0,5704.0,1.0
1|SubID[2],-80.280,56.549,-190.651,31.147,0.805,0.632,4943.0,5338.0,1.0
1|SubID[3],-18.194,54.091,-123.045,87.245,0.727,0.580,5521.0,5466.0,1.0
1|SubID[4],86.564,55.991,-23.450,196.580,0.885,0.632,3998.0,5255.0,1.0
1|SubID[5],16.176,54.572,-89.794,124.612,0.693,0.623,6224.0,5341.0,1.0
1|SubID[6],-29.556,54.291,-136.202,76.704,0.706,0.599,5919.0,5870.0,1.0
1|SubID[7],90.062,57.235,-18.894,203.873,0.818,0.574,4911.0,5624.0,1.0
1|SubID[8],-121.563,59.284,-237.698,-5.247,0.939,0.635,3991.0,4715.0,1.0
1|SubID[9],61.833,55.138,-48.092,168.061,0.754,0.582,5355.0,5863.0,1.0
1|SubID[10],-86.271,57.389,-196.695,26.347,0.802,0.594,5120.0,5511.0,1.0
1|SubID[11],31.719,53.664,-72.204,138.842,0.734,0.587,5352.0,5703.0,1.0
1|SubID[12],-40.362,55.072,-148.106,64.503,0.732,0.625,5633.0,5244.0,1.0
1|SubID[13],-35.901,55.519,-142.603,73.910,0.727,0.610,5803.0,5514.0,1.0
1|SubID[14],-68.344,56.376,-176.045,46.605,0.752,0.662,5600.0,5153.0,1.0
1|SubID[15],-20.303,54.335,-127.139,86.586,0.723,0.673,5661.0,5234.0,1.0
1|SubID[16],-93.838,56.586,-203.084,16.103,0.873,0.583,4205.0,5162.0,1.0
1|SubID[17],154.988,62.754,31.260,279.494,1.134,0.719,3106.0,3326.0,1.0
1|SubID[18],-31.885,54.373,-138.024,74.007,0.711,0.585,5860.0,5821.0,1.0
1|SubID[19],81.961,54.724,-24.562,190.790,0.790,0.574,4800.0,5681.0,1.0
1|SubID[20],13.327,54.580,-92.967,118.222,0.744,0.631,5377.0,6282.0,1.0
1|SubID[21],-101.290,56.567,-212.226,7.782,0.893,0.618,4010.0,4719.0,1.0
1|SubID[22],115.849,58.701,1.962,228.035,0.960,0.651,3723.0,3437.0,1.0
1|SubID[23],158.518,62.325,36.119,283.364,1.165,0.698,2883.0,3733.0,1.0
1|SubID[24],-47.716,54.903,-149.682,64.069,0.797,0.628,4756.0,4724.0,1.0
1|SubID[25],-1.608,54.453,-111.838,103.949,0.743,0.638,5359.0,5494.0,1.0
1|SubID[26],-29.025,54.948,-143.815,72.463,0.729,0.631,5697.0,5591.0,1.0
1|SubID[27],-39.123,54.984,-151.911,63.268,0.729,0.624,5706.0,5457.0,1.0
1|SubID[28],-19.712,54.698,-122.736,90.704,0.710,0.622,5967.0,5559.0,1.0
1|SubID[29],20.973,54.389,-78.404,135.203,0.692,0.614,6190.0,5381.0,1.0
1|SubID[30],-43.684,55.793,-158.544,60.376,0.751,0.649,5525.0,5733.0,1.0

In [16]:
model = bmb.Model("Q2_UnAwErrD ~ SleepCond + SleepOrder + (1|SubID)", data4)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED, mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCond, SleepOrder, 1|SubID_sigma, 1|SubID_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,94.235,13.234,69.384,119.819,0.271,0.192,2526.0,3604.0,1.0
Intercept,162.230,25.480,111.304,211.539,0.532,0.344,2312.0,3275.0,1.0
SleepCond,34.249,12.257,10.336,58.966,0.121,0.162,10226.0,5514.0,1.0
SleepOrder,-18.162,25.513,-68.759,32.271,0.557,0.347,2104.0,3454.0,1.0
1|SubID_sigma,119.684,23.771,72.904,166.815,0.618,0.361,1489.0,3031.0,1.0
1|SubID[1],65.653,64.318,-61.539,192.696,0.915,0.720,4933.0,5472.0,1.0
1|SubID[2],-84.835,66.336,-214.957,46.112,0.976,0.721,4638.0,5417.0,1.0
1|SubID[3],31.508,62.808,-94.983,151.334,0.894,0.720,4955.0,5633.0,1.0
1|SubID[4],98.140,66.231,-27.735,232.166,0.979,0.715,4592.0,5401.0,1.0
1|SubID[5],-3.771,63.934,-132.013,122.855,0.860,0.694,5514.0,5923.0,1.0
1|SubID[6],-86.269,65.485,-214.001,41.997,0.893,0.710,5369.0,5886.0,1.0
1|SubID[7],248.890,73.149,101.398,389.052,1.292,0.840,3259.0,4015.0,1.0
1|SubID[8],-106.091,65.957,-232.072,26.220,1.016,0.748,4224.0,4542.0,1.0
1|SubID[9],44.873,63.974,-78.149,171.861,0.890,0.715,5199.0,5402.0,1.0
1|SubID[10],-78.336,64.113,-207.594,43.870,0.939,0.672,4656.0,4879.0,1.0
1|SubID[11],23.631,63.285,-102.306,144.711,0.886,0.663,5098.0,5287.0,1.0
1|SubID[12],-39.362,64.467,-170.038,84.732,0.856,0.692,5645.0,5888.0,1.0
1|SubID[13],27.524,64.270,-96.387,154.569,0.809,0.695,6307.0,5521.0,1.0
1|SubID[14],-50.030,63.827,-172.709,76.625,0.848,0.709,5668.0,5998.0,1.0
1|SubID[15],-13.364,64.213,-133.769,115.462,0.853,0.742,5729.0,5857.0,1.0
1|SubID[16],-79.036,65.580,-208.069,50.808,0.947,0.711,4800.0,5479.0,1.0
1|SubID[17],221.156,71.322,84.470,359.755,1.162,0.811,3787.0,4902.0,1.0
1|SubID[18],-15.572,63.481,-133.992,114.852,0.847,0.723,5631.0,4849.0,1.0
1|SubID[19],94.412,65.798,-39.480,221.942,0.947,0.752,4836.0,4976.0,1.0
1|SubID[20],27.112,64.256,-99.320,152.861,0.983,0.762,4346.0,5230.0,1.0
1|SubID[21],-127.230,66.155,-263.141,-4.159,0.952,0.683,4823.0,5669.0,1.0
1|SubID[22],184.044,68.976,43.762,316.218,1.057,0.707,4237.0,5485.0,1.0
1|SubID[23],92.193,65.062,-43.732,213.056,0.972,0.723,4478.0,5171.0,1.0
1|SubID[24],-99.126,65.621,-234.742,26.656,1.027,0.732,4072.0,5316.0,1.0
1|SubID[25],-45.027,64.461,-175.731,78.074,0.854,0.750,5699.0,5753.0,1.0
1|SubID[26],-80.941,64.800,-212.637,43.322,1.053,0.723,3780.0,5196.0,1.0
1|SubID[27],-74.650,65.312,-206.858,48.147,0.930,0.717,4946.0,5632.0,1.0
1|SubID[28],-73.091,65.155,-208.014,48.173,0.901,0.734,5232.0,5313.0,1.0
1|SubID[29],-30.685,64.679,-153.586,98.027,0.829,0.707,6086.0,5590.0,1.0
1|SubID[30],-64.729,64.448,-194.988,60.006,0.884,0.781,5353.0,5453.0,1.0

In [17]:
model = bmb.Model("Q3_UnAwErrD ~ SleepCond + SleepOrder + (1|SubID)", data4)
#idata = model.fit(draws=2000, chains=4, random_seed=SEED,cores=1)
idata = model.fit(draws=2000, chains=4, random_seed=SEED, mp_ctx='forkserver')
az.summary(idata, hdi_prob=0.95)

Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [sigma, Intercept, SleepCond, SleepOrder, 1|SubID_sigma, 1|SubID_offset]

/Users/hanskirschner/Desktop/EAST/MORPHEUS_EAST_Analyses/EAST_Data_and_Code/Bayesian_linear_models/.venv/lib/python
3.12/site-packages/rich/live.py:256: UserWarning: install "ipywidgets" for Jupyter support
  warnings.warn('install "ipywidgets" for Jupyter support')

Sampling 4 chains for 1_000 tune and 2_000 draw iterations (4_000 + 8_000 draws total) took 9 seconds.

,mean,sd,hdi_2.5%,hdi_97.5%,mcse_mean,mcse_sd,ess_bulk,ess_tail,r_hat
sigma,97.830,13.683,72.759,124.497,0.257,0.179,2808.0,4731.0,1.0
Intercept,188.847,29.303,127.864,242.791,0.593,0.417,2448.0,3387.0,1.0
SleepCond,53.826,12.655,30.140,80.202,0.132,0.154,9194.0,5599.0,1.0
SleepOrder,-25.742,28.433,-83.273,29.738,0.562,0.399,2566.0,3296.0,1.0
1|SubID_sigma,137.234,25.474,89.120,188.073,0.588,0.399,1912.0,3131.0,1.0
1|SubID[1],78.215,69.613,-63.213,209.808,0.967,0.745,5201.0,5311.0,1.0
1|SubID[2],-95.973,70.731,-237.856,41.682,0.966,0.790,5357.0,5472.0,1.0
1|SubID[3],30.229,68.883,-104.764,167.672,0.945,0.806,5312.0,5102.0,1.0
1|SubID[4],132.425,70.459,-7.332,270.832,0.973,0.754,5254.0,5873.0,1.0
1|SubID[5],-46.565,69.749,-182.389,87.702,0.942,0.823,5466.0,5618.0,1.0
1|SubID[6],-91.257,69.250,-226.095,46.144,0.939,0.741,5455.0,5698.0,1.0
1|SubID[7],262.639,75.481,116.096,415.039,1.050,0.816,5171.0,5504.0,1.0
1|SubID[8],-145.592,71.125,-287.966,-6.326,1.007,0.777,4985.0,6072.0,1.0
1|SubID[9],25.253,68.288,-104.041,165.236,0.976,0.747,4891.0,5812.0,1.0
1|SubID[10],-75.823,69.870,-218.801,59.111,0.926,0.723,5702.0,5783.0,1.0
1|SubID[11],6.458,68.672,-130.688,139.945,0.954,0.735,5174.0,6100.0,1.0
1|SubID[12],-68.820,69.996,-203.426,70.525,0.976,0.727,5135.0,5332.0,1.0
1|SubID[13],-58.980,69.115,-201.298,66.624,0.907,0.761,5820.0,5294.0,1.0
1|SubID[14],-13.030,68.770,-149.659,118.746,0.945,0.778,5304.0,5313.0,1.0
1|SubID[15],29.200,69.383,-110.259,162.985,0.929,0.773,5573.0,5350.0,1.0
1|SubID[16],-79.287,70.852,-223.582,53.625,0.924,0.769,5882.0,6126.0,1.0
1|SubID[17],313.484,78.397,160.855,471.025,1.213,0.847,4183.0,5112.0,1.0
1|SubID[18],53.983,68.959,-82.985,189.875,0.954,0.767,5230.0,5358.0,1.0
1|SubID[19],60.588,70.254,-70.422,204.890,0.904,0.823,6032.0,5810.0,1.0
1|SubID[20],-1.740,68.350,-140.874,130.820,0.943,0.723,5259.0,5531.0,1.0
1|SubID[21],-134.404,70.838,-279.607,-1.869,0.956,0.755,5516.0,5163.0,1.0
1|SubID[22],203.469,74.175,51.365,344.164,1.088,0.779,4645.0,5758.0,1.0
1|SubID[23],98.935,70.240,-39.099,239.943,0.996,0.723,4948.0,5898.0,1.0
1|SubID[24],-119.625,69.721,-260.544,13.976,0.933,0.720,5568.0,5663.0,1.0
1|SubID[25],6.199,68.419,-127.503,142.514,0.993,0.765,4753.0,5752.0,1.0
1|SubID[26],-115.306,71.085,-254.581,25.995,0.999,0.774,5071.0,5360.0,1.0
1|SubID[27],-99.020,70.248,-233.445,40.099,0.954,0.742,5421.0,5757.0,1.0
1|SubID[28],-57.233,69.490,-195.256,76.554,0.955,0.771,5302.0,5445.0,1.0
1|SubID[29],-56.609,68.916,-189.497,78.012,0.926,0.727,5524.0,5756.0,1.0
1|SubID[30],-54.655,69.925,-194.329,82.414,0.989,0.788,5005.0,5194.0,1.0